# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DatabaseServerApi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.common.Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x44\x61tabaseServerApi.proto\x12\ncom.server\x1a\x0c\x43ommon.proto\"M\n\x1d\x43reateDatabaseOnServerRequest\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x62Id\x18\x02 \x01(\x05\x12\x10\n\x08password\x18\x03 \x01(\t\"B\n\x18\x44\x61tabaseOnServerResponse\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x61tabaseName\x18\x02 \x01(\t2\xf8\x04\n\x15\x44\x61tabaseServerService\x12\x61\n\x0e\x43reateDatabase\x12).com.server.CreateDatabaseOnServerRequest\x1a$.com.server.DatabaseOnServerResponse\x12I\n\x0c\x44ropDatabase\x12\x1d.com.common.DatabaseIdRequest\x1a\x1a.com.common.ResponseResult\x12W\n\rResetDatabase\x12 .com.common.ResetDatabaseRequest\x1a$.com.server.DatabaseOnServerResponse\x12_\n\x16UpdateDatabasePassword\x12).com.common.UpdateDatabasePasswordRequest\x1a\x1a.com.common.ResponseResult\x12W\n\x12UpdateDatabaseSize\x12%.com.common.UpdateDatabaseSizeRequest\x1a\x1a.com.common.ResponseResult\x12T\n\x10GetDatabaseStats\x12\x1d.com.common.DatabaseIdRequest\x1a!.com.common.DatabaseStatsResponse\x12H\n\tSendQuery\x12\x1c.com.common.SendQueryRequest\x1a\x1d.com.common.SendQueryResponse2p\n\x1a\x44\x61tabaseServerStatsService\x12R\n\x0eGetServerStats\x12\x1d.com.common.DatabaseIdRequest\x1a!.com.common.DatabaseStatsResponseB\x02P\x01\x62\x06proto3')



_CREATEDATABASEONSERVERREQUEST = DESCRIPTOR.message_types_by_name['CreateDatabaseOnServerRequest']
_DATABASEONSERVERRESPONSE = DESCRIPTOR.message_types_by_name['DatabaseOnServerResponse']
CreateDatabaseOnServerRequest = _reflection.GeneratedProtocolMessageType('CreateDatabaseOnServerRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEDATABASEONSERVERREQUEST,
  '__module__' : 'DatabaseServerApi_pb2'
  # @@protoc_insertion_point(class_scope:com.server.CreateDatabaseOnServerRequest)
  })
_sym_db.RegisterMessage(CreateDatabaseOnServerRequest)

DatabaseOnServerResponse = _reflection.GeneratedProtocolMessageType('DatabaseOnServerResponse', (_message.Message,), {
  'DESCRIPTOR' : _DATABASEONSERVERRESPONSE,
  '__module__' : 'DatabaseServerApi_pb2'
  # @@protoc_insertion_point(class_scope:com.server.DatabaseOnServerResponse)
  })
_sym_db.RegisterMessage(DatabaseOnServerResponse)

_DATABASESERVERSERVICE = DESCRIPTOR.services_by_name['DatabaseServerService']
_DATABASESERVERSTATSSERVICE = DESCRIPTOR.services_by_name['DatabaseServerStatsService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _CREATEDATABASEONSERVERREQUEST._serialized_start=53
  _CREATEDATABASEONSERVERREQUEST._serialized_end=130
  _DATABASEONSERVERRESPONSE._serialized_start=132
  _DATABASEONSERVERRESPONSE._serialized_end=198
  _DATABASESERVERSERVICE._serialized_start=201
  _DATABASESERVERSERVICE._serialized_end=833
  _DATABASESERVERSTATSSERVICE._serialized_start=835
  _DATABASESERVERSTATSSERVICE._serialized_end=947
# @@protoc_insertion_point(module_scope)
