services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80

  app:
    restart: always
    build:
      dockerfile: Dockerfile
    volumes:
      - ./docker/file_storage:/file_storage
      - ./src:/app/src
    command: python src/app.py

  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
      - ${DATABASE_DATA_PATH}:/var/lib/postgresql/data
    ports:
      - 5432:5432

networks:
  default:
    name: test
