# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.common.Common_pb2 as Common__pb2
import proto.register.DatabaseServerRegisterApi_pb2 as DatabaseServerRegisterApi__pb2


class DatabaseServerRegisterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UnregisterServer = channel.unary_unary(
                '/com.register.DatabaseServerRegisterService/UnregisterServer',
                request_serializer=DatabaseServerRegisterApi__pb2.DatabaseServerUnregisterRequest.SerializeToString,
                response_deserializer=Common__pb2.ResponseResult.FromString,
                )
        self.RegisterServer = channel.unary_unary(
                '/com.register.DatabaseServerRegisterService/RegisterServer',
                request_serializer=DatabaseServerRegisterApi__pb2.DatabaseServerRegisterRequest.SerializeToString,
                response_deserializer=Common__pb2.ResponseResult.FromString,
                )


class DatabaseServerRegisterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UnregisterServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseServerRegisterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UnregisterServer': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterServer,
                    request_deserializer=DatabaseServerRegisterApi__pb2.DatabaseServerUnregisterRequest.FromString,
                    response_serializer=Common__pb2.ResponseResult.SerializeToString,
            ),
            'RegisterServer': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterServer,
                    request_deserializer=DatabaseServerRegisterApi__pb2.DatabaseServerRegisterRequest.FromString,
                    response_serializer=Common__pb2.ResponseResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.register.DatabaseServerRegisterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DatabaseServerRegisterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UnregisterServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.register.DatabaseServerRegisterService/UnregisterServer',
            DatabaseServerRegisterApi__pb2.DatabaseServerUnregisterRequest.SerializeToString,
            Common__pb2.ResponseResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.register.DatabaseServerRegisterService/RegisterServer',
            DatabaseServerRegisterApi__pb2.DatabaseServerRegisterRequest.SerializeToString,
            Common__pb2.ResponseResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
