# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x43ommon.proto\x12\ncom.common\x1a\x1cgoogle/protobuf/struct.proto\" \n\x0eResponseResult\x12\x0e\n\x06result\x18\x01 \x01(\x08\"!\n\x11\x44\x61tabaseIdRequest\x12\x0c\n\x04\x64\x62Id\x18\x01 \x01(\x05\"B\n\x1dUpdateDatabasePasswordRequest\x12\x0c\n\x04\x64\x62Id\x18\x01 \x01(\x05\x12\x13\n\x0bnewPassword\x18\x02 \x01(\t\"B\n\x19UpdateDatabaseSizeRequest\x12\x0c\n\x04\x64\x62Id\x18\x01 \x01(\x05\x12\x17\n\x0fnewDatabaseSize\x18\x02 \x01(\x03\"A\n\x15\x44\x61tabaseStatsResponse\x12\x13\n\x0b\x63urrentSize\x18\x01 \x01(\x03\x12\x13\n\x0b\x66illPercent\x18\x02 \x01(\x02\"9\n\x14ResetDatabaseRequest\x12\x0c\n\x04\x64\x62Id\x18\x01 \x01(\x05\x12\x13\n\x0bnewPassword\x18\x02 \x01(\t\":\n\x11SendQueryResponse\x12%\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"/\n\x10SendQueryRequest\x12\x0c\n\x04\x64\x62Id\x18\x01 \x01(\x05\x12\r\n\x05query\x18\x02 \x01(\t\"\x07\n\x05\x45mptyB\x02P\x01\x62\x06proto3')



_RESPONSERESULT = DESCRIPTOR.message_types_by_name['ResponseResult']
_DATABASEIDREQUEST = DESCRIPTOR.message_types_by_name['DatabaseIdRequest']
_UPDATEDATABASEPASSWORDREQUEST = DESCRIPTOR.message_types_by_name['UpdateDatabasePasswordRequest']
_UPDATEDATABASESIZEREQUEST = DESCRIPTOR.message_types_by_name['UpdateDatabaseSizeRequest']
_DATABASESTATSRESPONSE = DESCRIPTOR.message_types_by_name['DatabaseStatsResponse']
_RESETDATABASEREQUEST = DESCRIPTOR.message_types_by_name['ResetDatabaseRequest']
_SENDQUERYRESPONSE = DESCRIPTOR.message_types_by_name['SendQueryResponse']
_SENDQUERYREQUEST = DESCRIPTOR.message_types_by_name['SendQueryRequest']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
ResponseResult = _reflection.GeneratedProtocolMessageType('ResponseResult', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSERESULT,
  '__module__' : 'Common_pb2'
  # @@protoc_insertion_point(class_scope:com.common.ResponseResult)
  })
_sym_db.RegisterMessage(ResponseResult)

DatabaseIdRequest = _reflection.GeneratedProtocolMessageType('DatabaseIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATABASEIDREQUEST,
  '__module__' : 'Common_pb2'
  # @@protoc_insertion_point(class_scope:com.common.DatabaseIdRequest)
  })
_sym_db.RegisterMessage(DatabaseIdRequest)

UpdateDatabasePasswordRequest = _reflection.GeneratedProtocolMessageType('UpdateDatabasePasswordRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEDATABASEPASSWORDREQUEST,
  '__module__' : 'Common_pb2'
  # @@protoc_insertion_point(class_scope:com.common.UpdateDatabasePasswordRequest)
  })
_sym_db.RegisterMessage(UpdateDatabasePasswordRequest)

UpdateDatabaseSizeRequest = _reflection.GeneratedProtocolMessageType('UpdateDatabaseSizeRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEDATABASESIZEREQUEST,
  '__module__' : 'Common_pb2'
  # @@protoc_insertion_point(class_scope:com.common.UpdateDatabaseSizeRequest)
  })
_sym_db.RegisterMessage(UpdateDatabaseSizeRequest)

DatabaseStatsResponse = _reflection.GeneratedProtocolMessageType('DatabaseStatsResponse', (_message.Message,), {
  'DESCRIPTOR' : _DATABASESTATSRESPONSE,
  '__module__' : 'Common_pb2'
  # @@protoc_insertion_point(class_scope:com.common.DatabaseStatsResponse)
  })
_sym_db.RegisterMessage(DatabaseStatsResponse)

ResetDatabaseRequest = _reflection.GeneratedProtocolMessageType('ResetDatabaseRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESETDATABASEREQUEST,
  '__module__' : 'Common_pb2'
  # @@protoc_insertion_point(class_scope:com.common.ResetDatabaseRequest)
  })
_sym_db.RegisterMessage(ResetDatabaseRequest)

SendQueryResponse = _reflection.GeneratedProtocolMessageType('SendQueryResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDQUERYRESPONSE,
  '__module__' : 'Common_pb2'
  # @@protoc_insertion_point(class_scope:com.common.SendQueryResponse)
  })
_sym_db.RegisterMessage(SendQueryResponse)

SendQueryRequest = _reflection.GeneratedProtocolMessageType('SendQueryRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDQUERYREQUEST,
  '__module__' : 'Common_pb2'
  # @@protoc_insertion_point(class_scope:com.common.SendQueryRequest)
  })
_sym_db.RegisterMessage(SendQueryRequest)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'Common_pb2'
  # @@protoc_insertion_point(class_scope:com.common.Empty)
  })
_sym_db.RegisterMessage(Empty)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _RESPONSERESULT._serialized_start=58
  _RESPONSERESULT._serialized_end=90
  _DATABASEIDREQUEST._serialized_start=92
  _DATABASEIDREQUEST._serialized_end=125
  _UPDATEDATABASEPASSWORDREQUEST._serialized_start=127
  _UPDATEDATABASEPASSWORDREQUEST._serialized_end=193
  _UPDATEDATABASESIZEREQUEST._serialized_start=195
  _UPDATEDATABASESIZEREQUEST._serialized_end=261
  _DATABASESTATSRESPONSE._serialized_start=263
  _DATABASESTATSRESPONSE._serialized_end=328
  _RESETDATABASEREQUEST._serialized_start=330
  _RESETDATABASEREQUEST._serialized_end=387
  _SENDQUERYRESPONSE._serialized_start=389
  _SENDQUERYRESPONSE._serialized_end=447
  _SENDQUERYREQUEST._serialized_start=449
  _SENDQUERYREQUEST._serialized_end=496
  _EMPTY._serialized_start=498
  _EMPTY._serialized_end=505
# @@protoc_insertion_point(module_scope)
