# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DatabaseServerApi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.common.Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x44\x61tabaseServerApi.proto\x12\ncom.server\x1a\x0c\x43ommon.proto\"M\n\x1d\x43reateDatabaseOnServerRequest\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x62Id\x18\x02 \x01(\x05\x12\x10\n\x08password\x18\x03 \x01(\t\"\x80\x01\n\x1d\x44\x61tabaseStatsOnServerResponse\x12\x13\n\x0b\x63urrentSize\x18\x01 \x01(\x03\x12\x13\n\x0b\x66illPercent\x18\x02 \x01(\x02\x12\x1b\n\x13\x64\x61tabaseAndUsername\x18\x03 \x01(\t\x12\x18\n\x10\x61llowConnections\x18\x04 \x01(\x08\"5\n\x16\x43reateDatabaseResponse\x12\x1b\n\x13\x64\x61tabaseAndUsername\x18\x01 \x01(\t2\xea\x05\n\x15\x44\x61tabaseServerService\x12_\n\x0e\x43reateDatabase\x12).com.server.CreateDatabaseOnServerRequest\x1a\".com.server.CreateDatabaseResponse\x12I\n\x0c\x44ropDatabase\x12\x1d.com.common.DatabaseIdRequest\x1a\x1a.com.common.ResponseResult\x12Z\n\rResetDatabase\x12%.com.common.DatabaseIdPasswordRequest\x1a\".com.server.CreateDatabaseResponse\x12k\n\x1eUpdateDatabaseAllowConnections\x12-.com.common.DatabaseIdConnectionsAllowRequest\x1a\x1a.com.common.ResponseResult\x12[\n\x16UpdateDatabasePassword\x12%.com.common.DatabaseIdPasswordRequest\x1a\x1a.com.common.ResponseResult\x12W\n\x12UpdateDatabaseSize\x12%.com.common.UpdateDatabaseSizeRequest\x1a\x1a.com.common.ResponseResult\x12\\\n\x10GetDatabaseStats\x12\x1d.com.common.DatabaseIdRequest\x1a).com.server.DatabaseStatsOnServerResponse\x12H\n\tSendQuery\x12\x1c.com.common.SendQueryRequest\x1a\x1d.com.common.SendQueryResponseB\x02P\x01\x62\x06proto3')



_CREATEDATABASEONSERVERREQUEST = DESCRIPTOR.message_types_by_name['CreateDatabaseOnServerRequest']
_DATABASESTATSONSERVERRESPONSE = DESCRIPTOR.message_types_by_name['DatabaseStatsOnServerResponse']
_CREATEDATABASERESPONSE = DESCRIPTOR.message_types_by_name['CreateDatabaseResponse']
CreateDatabaseOnServerRequest = _reflection.GeneratedProtocolMessageType('CreateDatabaseOnServerRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEDATABASEONSERVERREQUEST,
  '__module__' : 'DatabaseServerApi_pb2'
  # @@protoc_insertion_point(class_scope:com.server.CreateDatabaseOnServerRequest)
  })
_sym_db.RegisterMessage(CreateDatabaseOnServerRequest)

DatabaseStatsOnServerResponse = _reflection.GeneratedProtocolMessageType('DatabaseStatsOnServerResponse', (_message.Message,), {
  'DESCRIPTOR' : _DATABASESTATSONSERVERRESPONSE,
  '__module__' : 'DatabaseServerApi_pb2'
  # @@protoc_insertion_point(class_scope:com.server.DatabaseStatsOnServerResponse)
  })
_sym_db.RegisterMessage(DatabaseStatsOnServerResponse)

CreateDatabaseResponse = _reflection.GeneratedProtocolMessageType('CreateDatabaseResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEDATABASERESPONSE,
  '__module__' : 'DatabaseServerApi_pb2'
  # @@protoc_insertion_point(class_scope:com.server.CreateDatabaseResponse)
  })
_sym_db.RegisterMessage(CreateDatabaseResponse)

_DATABASESERVERSERVICE = DESCRIPTOR.services_by_name['DatabaseServerService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _CREATEDATABASEONSERVERREQUEST._serialized_start=53
  _CREATEDATABASEONSERVERREQUEST._serialized_end=130
  _DATABASESTATSONSERVERRESPONSE._serialized_start=133
  _DATABASESTATSONSERVERRESPONSE._serialized_end=261
  _CREATEDATABASERESPONSE._serialized_start=263
  _CREATEDATABASERESPONSE._serialized_end=316
  _DATABASESERVERSERVICE._serialized_start=319
  _DATABASESERVERSERVICE._serialized_end=1065
# @@protoc_insertion_point(module_scope)
