# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DatabaseServerRegisterApi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.common.Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x44\x61tabaseServerRegisterApi.proto\x12\x0c\x63om.register\x1a\x0c\x43ommon.proto\"0\n\x1f\x44\x61tabaseServerUnregisterRequest\x12\r\n\x05\x64\x62Url\x18\x01 \x01(\t\"\x99\x01\n\x1d\x44\x61tabaseServerRegisterRequest\x12\x11\n\tdbGrpcUrl\x18\x01 \x01(\t\x12\r\n\x05\x64\x62Url\x18\x02 \x01(\t\x12\x14\n\x0c\x64\x61tabaseType\x18\x03 \x01(\t\x12\x11\n\tfreeSpace\x18\x04 \x01(\x03\x12-\n\tdatabases\x18\x05 \x03(\x0b\x32\x1a.com.register.DatabaseInfo\"L\n\x0c\x44\x61tabaseInfo\x12\x0c\n\x04\x64\x62Id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x62Name\x18\x03 \x01(\t\x12\x0c\n\x04size\x18\x04 \x01(\x03\x32\xd9\x01\n\x1d\x44\x61tabaseServerRegisterService\x12]\n\x10UnregisterServer\x12-.com.register.DatabaseServerUnregisterRequest\x1a\x1a.com.common.ResponseResult\x12Y\n\x0eRegisterServer\x12+.com.register.DatabaseServerRegisterRequest\x1a\x1a.com.common.ResponseResultB\x02P\x01\x62\x06proto3')



_DATABASESERVERUNREGISTERREQUEST = DESCRIPTOR.message_types_by_name['DatabaseServerUnregisterRequest']
_DATABASESERVERREGISTERREQUEST = DESCRIPTOR.message_types_by_name['DatabaseServerRegisterRequest']
_DATABASEINFO = DESCRIPTOR.message_types_by_name['DatabaseInfo']
DatabaseServerUnregisterRequest = _reflection.GeneratedProtocolMessageType('DatabaseServerUnregisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATABASESERVERUNREGISTERREQUEST,
  '__module__' : 'DatabaseServerRegisterApi_pb2'
  # @@protoc_insertion_point(class_scope:com.register.DatabaseServerUnregisterRequest)
  })
_sym_db.RegisterMessage(DatabaseServerUnregisterRequest)

DatabaseServerRegisterRequest = _reflection.GeneratedProtocolMessageType('DatabaseServerRegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATABASESERVERREGISTERREQUEST,
  '__module__' : 'DatabaseServerRegisterApi_pb2'
  # @@protoc_insertion_point(class_scope:com.register.DatabaseServerRegisterRequest)
  })
_sym_db.RegisterMessage(DatabaseServerRegisterRequest)

DatabaseInfo = _reflection.GeneratedProtocolMessageType('DatabaseInfo', (_message.Message,), {
  'DESCRIPTOR' : _DATABASEINFO,
  '__module__' : 'DatabaseServerRegisterApi_pb2'
  # @@protoc_insertion_point(class_scope:com.register.DatabaseInfo)
  })
_sym_db.RegisterMessage(DatabaseInfo)

_DATABASESERVERREGISTERSERVICE = DESCRIPTOR.services_by_name['DatabaseServerRegisterService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _DATABASESERVERUNREGISTERREQUEST._serialized_start=63
  _DATABASESERVERUNREGISTERREQUEST._serialized_end=111
  _DATABASESERVERREGISTERREQUEST._serialized_start=114
  _DATABASESERVERREGISTERREQUEST._serialized_end=267
  _DATABASEINFO._serialized_start=269
  _DATABASEINFO._serialized_end=345
  _DATABASESERVERREGISTERSERVICE._serialized_start=348
  _DATABASESERVERREGISTERSERVICE._serialized_end=565
# @@protoc_insertion_point(module_scope)
